name: Unit tests (python versions)

on:
  push:
    branches:
      - main
  pull_request:
    # Run workflow when PR is changed, or when changed from draft to ready
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: Python unit tests
    runs-on: ubuntu-latest

    # Skip job if it's a draft PR
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      # - name: Install dependencies
      #   run: |
      #     sudo ./.github/workflows/install_dependencies.sh

      - name: Install dependencies
        run: |
          apt-get -qq update;
          apt-get install -y libopenblas-dev liblapack-dev
          wget https://github.com/LLNL/sundials/releases/download/v5.1.0/sundials-5.1.0.tar.gz
          tar xzf sundials-5.1.0.tar.gz
          mkdir build-sundials-5.1.0
          cd build-sundials-5.1.0/
          cmake -DLAPACK_ENABLE=ON -DSUNDIALS_INDEX_SIZE=64 -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE ../sundials-5.1.0/
          make install
          export SUNDIALS_INST=$GITHUB_WORKSPACE
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib:$LD_LIBRARY_PATH

      - name: print
        run: |
          echo $GITHUB_WORKSPACE
          echo $LD_LIBRARY_PATH
          echo $SUNDIALS_INST

      - name: Install models
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ./streamflow/
          python -m pip install -e ./streamflow/[dev,cvode]

      - name: run unit tests
        run: |
          python run-tests.py --unit
